services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: emo_project
      POSTGRES_PASSWORD: "15IEoq-rZWfP_TlNY4rAN1npBkg0gLzL"
    volumes:
      - emo_project_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "W007bsmSZSPN3UeTpNCYXwFlQPHPtN8P"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: emo_project_test
      POSTGRES_PASSWORD: "P8L22HdbNLUfu82giDT3CBgo-h20O1yQ"
    volumes:
      - emo_project_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "ILcbcIz6NrYWVcWC1VHMooLGdWQ4CBCg"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  emo_project_data:
  emo_project_test_data:
